MINUTES = (
    '',
    'One minute',
    'Two minutes',
    'Three minutes',
    'Four minutes',
    'Five',
    'Six minutes',
    'Seven minutes',
    'Eight minutes',
    'Nine minutes',
    'Ten',
    'Eleven minutes',
    'Twelve minutes',
    'Thirteen minutes',
    'Fourteen minutes',
    'Quarter',
    'Sixteen minutes',
    'Seventeen minutes',
    'Eighteen minutes',
    'Nineteen minutes',
    'Twenty',
    'Twenty-one minutes',
    'Twenty-two minutes',
    'Twenty-three minutes',
    'Twenty-four minutes',
    'Twenty-five',
    'Twenty-six minutes',
    'Twenty-seven minutes',
    'Twenty-eight minutes',
    'Twenty-nine minutes',
    'Half',
)

HOURS = (
    'Midnight',
    'One',
    'Two',
    'Three',
    'Four',
    'Five',
    'Six',
    'Seven',
    'Eight',
    'Nine',
    'Ten',
    'Eleven',
    'Twelve',
    'One',
    'Two',
    'Three',
    'Four',
    'Five',
    'Six',
    'Seven',
    'Eight',
    'Nine',
    'Ten',
    'Eleven',
    'Midnight',
)

PAST = 'past'
TO = 'to'
OCLOCK = 'o\'clock'