PORT = 7000
ALLOWED_IPS = [
    '127.0.0.1',
]

RESOLUTION = (1024, 768)
PADDING = 10

DATE_FONT = None
DATE_FONT_SIZE = 48

CLOCK_FONT = None
CLOCK_FONT_SIZE = int(RESOLUTION[1]/4)

BACKTIMER_FONT = CLOCK_FONT
BACKTIMER_FONT_SIZE = int(RESOLUTION[1]/6.6)
BACKTIMER_COUNT = 30 # 60 backtimes to :00, 30 backtimes to every :00, :30 - etc

INFO_FONT = DATE_FONT
INFO_FONT_SIZE = 32

PROGRESS_FONT = INFO_FONT
PROGRESS_FONT_SIZE = INFO_FONT_SIZE

NOW_PLAYING_HEIGHT = 50
